feat: 기본 레이아웃 구성
croco-dev/darun pull request #41
Opened 2024-02-12 13:06 UTC by ddarkr

![image](https://github.com/croco-dev/darun/assets/6638675/701f4096-8846-40e0-ba68-96e6a4a6a0d5)

- 기본 레이아웃을 구성합니다.

2024-02-12 13:15 UTC, kang-heewon requested changes

2024-02-12 13:15 UTC, kang-heewon commented on libs/shared/ui-foundation/src/libs/Container/Container.tsx
> +export function Container({ children }: { children: ReactNode }) {
Container 이름이 너무 범용적이라서 ContentArea 정도로 변경하면 좋을듯합니당

2024-02-12 13:15 UTC, kang-heewon commented on libs/shared/ui-foundation/src/libs/Logo/Logo.tsx
> +  colorType?: 'light' | 'dark';
colorMode 같은게 더 맞지 않으려나...?  colorScheme...?

2024-02-12 13:15 UTC, kang-heewon commented on libs/shared/ui-foundation/src/libs/Logo/Logo.tsx
> +const dark = '#111111';
나중엔 테마에서 가져오면 좋을듯

2024-02-12 13:15 UTC, kang-heewon commented on libs/shared/ui-foundation/src/libs/TextButton/TextButton.tsx
> +  return <ContainedButton kind={'text'}>{children}</ContainedButton>;
이거 ContainedButton 구현 가져오지 말고 BaseButton으로 구현하는게 더 좋을거 같아요.
이러면 ContainedButton와 TextButton를 구분하는 이유가 없는데다가 kind text 인터페이스가 외부에 노출되는 거라서요.

2024-02-12 13:15 UTC, kang-heewon commented on libs/shared/ui-layout/src/libs/Footer/Footer.tsx
> +);
https://www.kuma-ui.com/docs/Components/Text 
로 충분히 대응할 수 있지 않아요?

2024-02-12 13:15 UTC, kang-heewon commented on libs/shared/ui-layout/src/libs/Footer/Footer.tsx
> +const Dot = () => <LinkText type={'dot'}>•</LinkText>;
이것도 컴포넌트로 마는게 맞을까...

2024-02-12 13:16 UTC, kang-heewon commented on libs/shared/ui-layout/src/libs/Header/Header.tsx
> +const LinkItem = ({ href, children }: { href?: string; children: ReactNode }) => (
one file one component를 지켜주세요. 유지보수를 어렵게 하는 제1원인입니다...

2024-02-12 13:16 UTC, kang-heewon commented on libs/shared/ui-layout/src/libs/Header/Header.tsx
> +const LinkItem = ({ href, children }: { href?: string; children: ReactNode }) => (
href 정도만 필요하다면 Link컴포넌트 정도로 처리해도 될 거 같아요

2024-02-12 13:17 UTC, ddarkr commented on libs/shared/ui-foundation/src/libs/Container/Container.tsx
> +export function Container({ children }: { children: ReactNode }) {
수용

2024-02-12 13:18 UTC, ddarkr commented on libs/shared/ui-foundation/src/libs/Logo/Logo.tsx
> +  colorType?: 'light' | 'dark';
schema 수용

2024-02-12 13:18 UTC, ddarkr commented on libs/shared/ui-foundation/src/libs/Logo/Logo.tsx
> +const dark = '#111111';
수용

2024-02-12 13:33 UTC, ddarkr commented on libs/shared/ui-foundation/src/libs/Logo/Logo.tsx
> +const dark = '#111111';
수용 실패... kuma-ui에 emotion theme처럼 useTheme 느낌의 기능이 없어서 나중에 Context 만들어서 가져와야 할 것으로 보입니다.

2024-02-12 13:34 UTC, ddarkr commented on libs/shared/ui-foundation/src/libs/TextButton/TextButton.tsx
> +  return <ContainedButton kind={'text'}>{children}</ContainedButton>;
수용 (BaseButton 만들고 타입 분리 예정)

2024-02-12 13:36 UTC, ddarkr commented on libs/shared/ui-layout/src/libs/Footer/Footer.tsx
> +const Dot = () => <LinkText type={'dot'}>•</LinkText>;
이건 귀찮아서 말았던거...

2024-02-12 13:37 UTC, ddarkr commented on libs/shared/ui-layout/src/libs/Footer/Footer.tsx
> +);
Text로 바꿀게요 근데 스타일 요소때매 컴포넌트 자체는 납두는게 맞지 않을가

2024-02-12 18:00 UTC, kang-heewon commented on apps/service-web/app/layout.tsx
> +                <Layout>{children}</Layout>
Layout은 각 페이지 root에서 지정해주는게 제일 좋을거 같아요.
이러면 layout이 다른 페이지를 만드는것 자체가 어려워지니까요

2024-02-12 18:02 UTC, kang-heewon commented on libs/shared/ui-foundation/src/libs/BaseButton/BaseButton.tsx
> +  dark: {
이게 dark보단 primary가 되고 유저가 선택한 colorMode에 따라서 알아서 바뀌어야하는거 아니에요?

2024-02-12 18:03 UTC, kang-heewon commented on libs/shared/ui-foundation/src/libs/BaseButton/BaseButton.tsx
> +  dark: {
요런식으로 구현하면 모든 컴포넌트가 화이트 & 다크 스타일을 일일히 다 구현해야할텐데... 
그거보다는 컬러체계 자체가 컬러모드를 지원하면 쉽지 않을까요?

2024-02-12 18:04 UTC, kang-heewon commented on libs/shared/ui-layout/src/libs/Footer/Footer.tsx
> +  <Box as={'footer'} py={28}>
기본적으로 Box보단 Flex를 쓰기를 추천드립니다

2024-02-12 18:04 UTC, kang-heewon commented on libs/shared/ui-layout/src/libs/Header/Header.tsx
> +  <Box as={'nav'} display={'flex'} width={'100%'}>
여긴 Flex쓰는게 맞는거 같아요

2024-02-12 18:05 UTC, kang-heewon commented on libs/shared/ui-layout/src/libs/HeaderQuickItem/HeaderQuickItem.tsx
> +  </Box>
a 태그는 https://www.kuma-ui.com/docs/Components/Link 이걸로 구현하시죠

2024-02-12 18:06 UTC, kang-heewon commented on libs/shared/ui-layout/src/libs/HeaderQuickItem/HeaderQuickItem.tsx
> +  </Box>
애초에 이 컴포넌트가 별로 안필요할거같긴해요

2024-02-14 13:16 UTC, kang-heewon approved these changes

2024-02-14 13:16 UTC, merged